spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:test;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa

logging:
  level:
    org.springframework:
      jdbc: debug
