spring:
  h2:
    console:
      enabled: true
  datasource:
    url:  jdbc:h2:tcp://localhost/~/subway;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
  sql:
    init:
      mode: always
      schema-locations: classpath:/schema.sql
      data-locations:
logging:
  level:
    org.springframework:
      jdbc: debug
